source 'https://github.com/CocoaPods/Specs.git'
# use_frameworks!

target 'BXSocialAuth_Example', :exclusive => true do
  pod 'BXSocialAuth', :path => '../'
end

target 'BXSocialAuth_Tests', :exclusive => true do
  # pod 'BXSocialAuth', :path => '../'
  pod 'Specta'
  pod 'Expecta'
  pod 'OCMock'
end
