source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'BXSocialAuth_Example' do
  pod 'BXSocialAuth', :path => '../'
end

target 'BXSocialAuth_Tests' do
  # pod 'BXSocialAuth', :path => '../'
  pod 'Specta'
  pod 'Expecta'
  pod 'OCMock'
end
